

DROP TABLE IF EXISTS course;
DROP TABLE IF EXISTS entity1;
DROP TABLE IF EXISTS office_hour;
DROP TABLE IF EXISTS queue;
DROP TABLE IF EXISTS student;
DROP TABLE IF EXISTS ta_list;
DROP TABLE IF EXISTS user;